# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ize00113 < Formula
  desc "IZE is an opinionated infrastructure wrapper that allows to use multiple tools in one infra"
  homepage "https://ize.sh/"
  version "0.0.113"
  license "MIT"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kobrikx/test/releases/download/0.0.113/ize_0.0.113_darwin_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "7fe42dd62dd7e7839da1d7b09ad8e86545bb39a76fdafdc5006c2714a16ce43a"

      def install
        bin.install "ize"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kobrikx/test/releases/download/0.0.113/ize_0.0.113_darwin_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "695d433d9507dc226686d6672553c8dc0e96730e75bbe69faa342de78f6fc860"

      def install
        bin.install "ize"
      end
    end
  end

  conflicts_with "ize-dev"

  test do
    system "#{bin}/ize"
  end
end
