# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ize < Formula
  desc "IZE is an opinionated infrastructure wrapper that allows to use multiple tools in one infra"
  homepage "https://ize.sh/"
  version "0.0.11"
  license "MIT"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kobrikx/test/releases/download/0.0.11/ize_0.0.11_darwin_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "1f4abc6444d177927f8e9d9eab59a056d92ce40dd5edb38c0673724f6f8d9a7b"

      def install
        bin.install "ize"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kobrikx/test/releases/download/0.0.11/ize_0.0.11_darwin_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "1aee4356dbebaa6b17553c37f872cfebccff6fec6676ce003ae8da9c0594b90b"

      def install
        bin.install "ize"
      end
    end
  end

  conflicts_with "ize-dev"

  test do
    system "#{bin}/ize"
  end
end
