# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ize < Formula
  desc "IZE is an opinionated infrastructure wrapper that allows to use multiple tools in one infra"
  homepage "https://ize.sh/"
  version "0.0.11"
  license "MIT"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kobrikx/test/releases/download/0.0.11/ize_0.0.11_darwin_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "d3fab32ffbd1f4f283589892a2a97e5003b035882dea7041574718b01e79b0b7"

      def install
        bin.install "ize"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kobrikx/test/releases/download/0.0.11/ize_0.0.11_darwin_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "188efc556431289e89e7257f6994b79f12d65d0d2270d7c53905ecd1110fe110"

      def install
        bin.install "ize"
      end
    end
  end

  conflicts_with "ize-dev"

  test do
    system "#{bin}/ize"
  end
end
